/*
 * This source file was generated by the Gradle 'init' task
 */
package crowd_simulation;

import processing.core.PApplet;

public class App extends PApplet {
    @Override
    public void settings() {
        size(800, 600);
    }

    @Override
    public void setup() {
        background(255);
    }

    @Override
    public void draw() {
        fill(255, 0, 0);
        ellipse(mouseX, mouseY, 20, 20);
    }

    public static void main(String[] args) {
        PApplet.main("crowd_simulation.App");
    }
}
